export const environment = {
     production: true,
     gatewayUrl: 'https://lab.vallegrande.edu.pe/jass/ms-gateway',
     apiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-user/api/v1',
     organizations: 'https://lab.vallegrande.edu.pe/jass/ms-organization/api/management/organizations',
     complaintsIncidentsApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-claim-incidents/api/admin',
     distribution: 'https://lab.vallegrande.edu.pe/jass/ms-distribution/api/admin',
     testingPoint: 'https://lab.vallegrande.edu.pe/jass/ms-water-quality/api/admin/quality/sampling-points',
     dailyRecords: 'https://lab.vallegrande.edu.pe/jass/ms-water-quality/api/admin/quality/reports/daily-records',
     zonas: 'https://lab.vallegrande.edu.pe/jass/ms-organization/api/admin/zones',
     street: 'https://lab.vallegrande.edu.pe/jass/ms-organization/api/admin/streets',
     qualityTest: 'https://lab.vallegrande.edu.pe/jass/ms-water-quality/api/admin/quality/tests',
     users: 'https://lab.vallegrande.edu.pe/jass/ms-user/api/v1/users/all',
     incidents: 'https://vg-ms-claims-production.up.railway.app/api/v1',
     inventoryApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-inventory/api/v1',
     infrastructureApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-infrastructure/api/management',
     reniecApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-users/users/reniec/dni',
     payments: 'https://lab.vallegrande.edu.pe/jass/ms-payments/api/admin/payments',

};
